name = "uptimeflare_worker"
main = "src/index.ts"
compatibility_date = "2025-04-02"
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "UPTIMEFLARE_KV"
id = "1b169745203945cdafbf87f2220c7bc8"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RemoteChecker"]

[[durable_objects.bindings]]
name = "REMOTE_CHECKER_DO"
class_name = "RemoteChecker"
