name = "uptimeflare_worker"
main = "src/index.ts"
compatibility_date = "2025-04-02"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "UPTIMEFLARE_D1"
database_name = "uptimeflare_d1"
database_id = "7968f3b6-46b4-40ed-bba8-3a477ad3519c"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RemoteChecker"]

[[durable_objects.bindings]]
name = "REMOTE_CHECKER_DO"
class_name = "RemoteChecker"
